trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  workerType: n1-standard-4
  parameterServerType: n1-standard-4
  evaluatorType: n1-standard-4
  workerCount: 1
  parameterServerCount: 1
  evaluatorCount: 1